# -*- coding: utf-8 -*-
"""书斋V65 PyInstaller 打包配置"""
import os, sys

# 项目根目录（spec文件所在的目录）
ROOT = SPECPATH

a = Analysis(
    ['server.py'],
    pathex=[ROOT],
    binaries=[],
    datas=[],  # 前端文件由build.py手动复制
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'pydantic',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'h11',
        'json',
        'hashlib',
        'hmac',
        'secrets',
        'base64',
        # 项目模块
        'backend',
        'backend.routers',
        'backend.routers.auth_router',
        'backend.routers.project',
        'backend.routers.chapter',
        'backend.routers.ai_router',
        'backend.routers.file_router',
        'backend.routers.validate',
        'backend.routers.ledger',
        'backend.routers.world_router',
        'backend.routers.workflow',
        'backend.routers.generate',
        'backend.routers.memory',
        'backend.routers.knowledge_base',
        'backend.routers.deconstruct',
        'backend.routers.storyboard',
        'backend.routers.chapter_check',
        'backend.routers.sync',
        'backend.routers.stats',
        'backend.routers.export',
        'backend.routers.templates',
        'backend.routers.chat',
        'backend.routers.agent',
        'backend.services',
        'backend.services.project_service',
        'backend.services.vector_memory',
        'backend.services.deconstruct_service',
        'backend.services.storyboard_service',
        'backend.services.audit',
        'backend.auth',
        'backend.project',
        'backend.generator',
        'backend.ledger',
        'backend.world_settings',
        'backend.ai_client',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'pandas', 'numpy', 'scipy', 'PIL', 'cv2', 'torch', 'transformers'],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='书斋V65',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='书斋V65',
)
